### ISSUE TITLE
SVHN datasets avaliable?

### ISSUE THREAD

**Issue by zhuqunxi** [EmilienDupont/augmented-neural-odes#9]

**Comment by EmilienDupont** [comment]
Hi @zhuqunxi! Did you solve your problem?

**Comment by zhuqunxi** [comment]
> Hi @zhuqunxi! Did you solve your problem?

Hi Emilien, Thank you for your prompt reply. I think I have solved it by processing the same way of MNIST data from the pytorch libary. 

Now, I have an another question for the anode. In your anode papaer, I found the number of parameters of each model are fixed almost the same, but I think this may lead to other problem, i.e., resulting in 1) different number of filters 2) different number of parameters after feature extraction.  These two effects may influence the result a lot.  Since anode with the augmentation, the final feature will be of high dimension, this may lead to make the classification more easily. I don't know which effect is most important. There are several factors, i.e., filters, paramters of last layer, etc, wihch confused me in the last days. 

Could you please give me some your opinion on such a case? 

Thanks advance.

Best regards

Qunxi

**Comment by EmilienDupont** [comment]
Hi Qunxi,

You are right that there are many factors influencing the performance of the model including number of filters, number of parameters in last layer, number of augmented dimensions and so on. In general it is hard to pinpoint exactly which part of the model makes it perform well, especially since each of the factors likely interact with each other. In the paper, we tried to fix the number of parameters of the model (which also fixes the number of filters) in total and then vary the number of augmented dimensions to show that more augmented dimensions tend to help up to a point (e.g. 5-10 augmented channels). However, we have not run experiments on how the number of parameters in the last layer affects performance. It would be interesting to run these experiments to compare model performance but I have not done it yet :)

**Comment by zhuqunxi** [comment]
> Hi Qunxi,
> 
> You are right that there are many factors influencing the performance of the model including number of filters, number of parameters in last layer, number of augmented dimensions and so on. In general it is hard to pinpoint exactly which part of the model makes it perform well, especially since each of the factors likely interact with each other. In the paper, we tried to fix the number of parameters of the model (which also fixes the number of filters) in total and then vary the number of augmented dimensions to show that more augmented dimensions tend to help up to a point (e.g. 5-10 augmented channels). However, we have not run experiments on how the number of parameters in the last layer affects performance. It would be interesting to run these experiments to compare model performance but I have not done it yet :)

Hi Emilien,

I agree with you that there are still a lot of interesting work to do. Overall, the anode method really inspired me a lot. Thanks for your help.  

Have a good weekend.

Qunxi
